### ISSUE TITLE
Need help with dxvk-async build for dxvk 1.7.2 

### ISSUE THREAD

**Issue by seanmacky** [Sporif/dxvk-async#5] opened 2020-11-29 23:47 UTC
Hello, can someone help me with building and patching the latest DXVK

I'm using this on Windows with GW2 and the Async build is amazing with dx9 !

Can someone please patch the latest Version 1.7.2 with the  Dxvk-Async build and upload the tar.gz here so i can use the 64 bit d'll's

I'm using this on Windows and i'm a noob with the building part ( don't use Linux )

Someone uploaded 1.7.1 with the async patch here https://github.com/doitsujin/dxvk/issues/1817

But there have been 26 commits to the master 1.7.2 since then ( plus version 1.7.2 is faster with gw2 )

Happy to donate $5 or $10 for the help 👍 
Thank you :)

**Comment by JustinSpedding** [comment] 2020-11-30 00:04
I built this on Linux, but I never tried running dxvk on Windows before. So idk if it will work for you, but it works for me on Linux. Anyway, I included the async patch and this pull request that speeds up shader compilation times: https://github.com/doitsujin/dxvk/pull/1582. It also includes commits up to https://github.com/doitsujin/dxvk/commit/e79e8b90626de8c6e812cada8ca0548e37553f68

[dxvk-async.zip](https://github.com/Sporif/dxvk-async/files/5613154/dxvk-async.zip)

**Comment by seanmacky** [comment] 2020-11-30 00:05
> I built this on Linux, but I never tried running dxvk on Windows before. So idk if it will work for you, but it works for me on Linux. Anyway, I included the async patch and this pull request that speeds up shader compilation times: [doitsujin/dxvk#1582](https://github.com/doitsujin/dxvk/pull/1582). It also includes commits up to [doitsujin/dxvk@e79e8b9](https://github.com/doitsujin/dxvk/commit/e79e8b90626de8c6e812cada8ca0548e37553f68)
> 
> [dxvk-async.zip](https://github.com/Sporif/dxvk-async/files/5613154/dxvk-async.zip)

That's amazing thank you so much !!!!!! :) :) :) :)

**Comment by seanmacky** [comment] 2020-11-30 07:36
> 
> 
> I built this on Linux, but I never tried running dxvk on Windows before. So idk if it will work for you, but it works for me on Linux. Anyway, I included the async patch and this pull request that speeds up shader compilation times: [doitsujin/dxvk#1582](https://github.com/doitsujin/dxvk/pull/1582). It also includes commits up to [doitsujin/dxvk@e79e8b9](https://github.com/doitsujin/dxvk/commit/e79e8b90626de8c6e812cada8ca0548e37553f68)
> 
> [dxvk-async.zip](https://github.com/Sporif/dxvk-async/files/5613154/dxvk-async.zip)

Hmmmm it wouldn't work ! 

Maybe it only works up to 1.7.1 although the patch did mention 1.7.2 !

Thanks for trying

**Comment by JustinSpedding** [comment] 2020-11-30 14:11
My guess is that, because I built it on Linux with the Linux version of minGW, the dlls only work on Linux. There is probably a way to build 1.7.2 with async to work on Windows, but idk how. Maybe the person that built the 1.7.1 dlls can help.

**Comment by seanmacky** [comment] 2020-12-01 08:34
> My guess is that, because I built it on Linux with the Linux version of minGW, the dlls only work on Linux. There is probably a way to build 1.7.2 with async to work on Windows, but idk how. Maybe the person that built the 1.7.1 dlls can help.

Thanks again for trying to help. I spoke with someone on discord and they said it's because the build you did included the pull request re shader compilation time. They said to try just building with the latest 1.7.2 and the async patch and it should work 😊

**Comment by Sporif** [comment] 2020-12-01 08:53
@seanmacky I just created a [1.7.2 release](https://github.com/Sporif/dxvk-async/releases/tag/1.7.2) with only the Async patch, you can try it out.

**Comment by seanmacky** [comment] 2020-12-01 10:07
> @seanmacky I just created a [1.7.2 release](https://github.com/Sporif/dxvk-async/releases/tag/1.7.2) with only the Async patch, you can try it out.

Thank you my friend! I will try this out in an hour or so when I get home 😁 much appreciated 😄

**Comment by Squall-Leonhart** [comment] 2020-12-03 03:08
> My guess is that, because I built it on Linux with the Linux version of minGW, the dlls only work on Linux. There is probably a way to build 1.7.2 with async to work on Windows, but idk how. Maybe the person that built the 1.7.1 dlls can help.

@JustinSpedding  that shouldn't have anything to do with it, the DLL is a DLL, what it looks like is you've broken some code in your local copy that causes allocatelocallyuniqueid to be sought out in the vulkan loader instead of the windows libraries.

**Comment by JustinSpedding** [comment] 2020-12-03 14:44
> > My guess is that, because I built it on Linux with the Linux version of minGW, the dlls only work on Linux. There is probably a way to build 1.7.2 with async to work on Windows, but idk how. Maybe the person that built the 1.7.1 dlls can help.
> 
> @JustinSpedding that shouldn't have anything to do with it, the DLL is a DLL, what it looks like is you've broken some code in your local copy that causes allocatelocallyuniqueid to be sought out in the vulkan loader instead of the windows libraries.

hmm I am not sure how that happened. How did you figure out that the problem is a bad call `allocatelocallyuniqueid`? And is that something that only becomes an issue when running on Windows?

**Comment by Squall-Leonhart** [comment] 2020-12-03 15:18
allocatelocallyuniqueid is exported by Advapi32.dll, and afaik is only used once in the entire dxvk source code.

The error that sean encountered (if its the same as my experience) was that the function was being looked up in vulkan-1.dll instead of the intended dll.

**Comment by seanmacky** [comment] 2020-12-06 08:05
> allocatelocallyuniqueid is exported by Advapi32.dll, and afaik is only used once in the entire dxvk source code.
> 
> The error that sean encountered (if its the same as my experience) was that the function was being looked up in vulkan-1.dll instead of the intended dll.

Yes thats the error I got! Does the latest dxvk 1.7.3 include this doitsujin/dxvk#1582 for speedier shader compilation times? It it possible to get a patched 1.7.3 that includes the improvements made from #1582? Thanks guys

**Comment by Kron4ek** [comment] 2020-12-06 19:04
@seanmacky Here is the dxvk-1.7.3 build with the async patch and [#1582 PR](doitsujin/dxvk#1582) applied. Works fine for me on Linux, don't know if it will work on Windows.

[dxvk-async-1.7.3.tar.gz](https://github.com/Sporif/dxvk-async/files/5649367/dxvk-async-1.7.3.tar.gz)

**Comment by seanmacky** [comment] 2020-12-15 06:15
> @seanmacky Here is the dxvk 1.7.3 build with the async patch and [#1582 PR](https://github.com/doitsujin/dxvk/pull/1582) applied. Works fine for me on Linux, don't know if it will work on Windows.
> 
> [dxvk-async-1.7.3.tar.gz](https://github.com/Sporif/dxvk-async/files/5649367/dxvk-async-1.7.3.tar.gz)

Hey mate just saw your reply ! thank you very much i'll test this out tonight ~ :)

**Comment by seanmacky** [comment] 2021-02-19 07:56
> 
> 
> @seanmacky Here is the dxvk 1.7.3 build with the async patch and [#1582 PR](https://github.com/doitsujin/dxvk/pull/1582) applied. Works fine for me on Linux, don't know if it will work on Windows.
> 
> [dxvk-async-1.7.3.tar.gz](https://github.com/Sporif/dxvk-async/files/5649367/dxvk-async-1.7.3.tar.gz)

Hi Kron4ek.   DXVK 1.8 was just released https://github.com/doitsujin/dxvk/releases/tag/v1.8 

Are you able to help by building 1.8 with the ASYNC patch and  #1582 PR applied ?

Thank you for your help , i really appreciate it !  Sean

**Comment by Kron4ek** [comment] 2021-02-19 08:26
@seanmacky Sure.

[dxvk-1.8-async.tar.gz](https://github.com/Sporif/dxvk-async/files/6008580/dxvk-1.8-async.tar.gz)

**Comment by Sporif** [comment] 2021-03-11 16:28
Closing this issue, if you want custom builds open a discussion.

**Closed by Sporif** 2021-03-11 16:28 UTC
